# SPDX-FileCopyrightText: 2023 Friedrich-Alexander-Universitat Erlangen-Nurnberg
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Check paths for windows

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check-paths-for-windows:
    name: Check paths for Windows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Check paths for Windows
        run: node ./tools/scripts/check-for-invalid-windows-paths.mjs
